version: '3.8'

services:
  backend:
    image: openjdk:17-jdk
    container_name: foodstockmate-backend
    volumes:
      - ./foodstockmate-0.0.1-SNAPSHOT.jar:/app.jar
    working_dir: /
    command: ["java", "-jar", "/app.jar"]
    ports:
      - "8080:8080"
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
